# This is a basic workflow to help you get started with Actions

name: win

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setting up git
        run: |
          git config --global user.name 'Release bot'
          git fetch
          git checkout $GITHUB_HEAD_REF

      - name: Creating output file
        run: |
          bash
          tmp="Hello, world"
          echo tmp
          mkdir -p out
          echo "Hello, world!!!" > out/release.txt
          echo "$(date +"%Y-%m-%d %T"): on branch $GITHUB_HEAD_REF" >> out/release-notes.txt
          exit
      - name: Printing files
        run: |
          ls out

      - name: Commiting changes
        run: |
          git add -A
          git commit -m "Release from branch $GITHUB_HEAD_REF generated"
          git push
      
